---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Vatu:    PHP Compatibility
# Version: 2.0.0

name: "PHP Compatibility"

on:
  workflow_dispatch:

    inputs:

      branch:
        type: string
        description: "Choose the branch to run this test against."
        default: 'main'

      php-version:
        description: "Array of Version(s) of PHP to test against. Eg, `['8.3','8.4']`"
        required: false
        type: string
        default: "['8.3','8.4']"

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  php-compatibility:

    name: 'PHP Compatibility'
    uses: 'vatu-team/workflows/.github/workflows/php-compatibility.yml@1.12.0'
    with:
      runs-on: 'self-hosted'
      branch: ${{ inputs.branch }}
      php-version: ${{ inputs.php-version }}
    secrets: inherit
